# Generated by Django 2.1.5 on 2019-02-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('day', models.CharField(blank=True, max_length=7, null=True)),
                ('startTime', models.CharField(blank=True, max_length=8, null=True)),
                ('endTime', models.CharField(blank=True, max_length=9, null=True)),
                ('location', models.CharField(blank=True, max_length=16, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('catalogCode', models.CharField(blank=True, max_length=3, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=1600, null=True)),
                ('career', models.CharField(blank=True, max_length=10, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('asString', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('component', models.CharField(blank=True, max_length=3, null=True)),
                ('classType', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('enrollStatus', models.CharField(blank=True, max_length=1, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=33, null=True)),
                ('campus', models.CharField(blank=True, max_length=4, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('autoEnroll', models.CharField(blank=True, max_length=5, null=True)),
                ('topic', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('consent', models.CharField(blank=True, max_length=16, null=True)),
                ('gradingBasis', models.CharField(blank=True, max_length=16, null=True)),
                ('instructionMode', models.CharField(blank=True, max_length=16, null=True)),
                ('units', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('classUrl', models.CharField(blank=True, max_length=64, null=True)),
                ('instructorUId', models.CharField(blank=True, max_length=12, null=True)),
                ('examStatus', models.CharField(blank=True, max_length=9, null=True)),
                ('examDate', models.DateField(blank=True, null=True)),
                ('examStartTime', models.CharField(blank=True, max_length=8, null=True)),
                ('examEndTime', models.CharField(blank=True, max_length=8, null=True)),
                ('examLocation', models.CharField(blank=True, max_length=16, null=True)),
                ('asString', models.CharField(blank=True, max_length=32, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(blank=True, max_length=3, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('publisher', models.CharField(blank=True, max_length=32, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('courseClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.CourseClass')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.Faculty'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.Term'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.Subject'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='courseClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.CourseClass'),
        ),
    ]
