# Generated by Django 2.1.5 on 2019-02-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchCourse', '0002_auto_20190211_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
