# Generated by Django 2.1.5 on 2019-02-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchCourse', '0003_auto_20190211_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='courseClass',
        ),
        migrations.DeleteModel(
            name='Textbook',
        ),
    ]
