# Generated by Django 2.1.7 on 2019-02-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchCourse', '0004_auto_20190212_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='calendarCode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
