# Generated by Django 2.1.7 on 2019-04-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searchCourse', '0008_auto_20190309_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchCourse.CourseClass')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
