# Generated by Django 2.1.7 on 2019-04-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchCourse', '0009_classcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcart',
            name='courseClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseClasses', to='searchCourse.CourseClass'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='courseClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classTimes', to='searchCourse.CourseClass'),
        ),
    ]
